[package]
name = "recode_rs"
version = "1.0.0"
authors = ["Henri Sivonen <hsivonen@hsivonen.fi>"]

[features]
simd-accel = ["encoding_rs/simd-accel"]
no-static-ideograph-encoder-tables = ["encoding_rs/no-static-ideograph-encoder-tables"]
parallel-utf8 = ["encoding_rs/parallel-utf8"]

[dependencies]
getopts = "0.2.14"
encoding_rs = "0.4.0"
