[package]
name = "recode_rs"
version = "1.0.3"
authors = ["Henri Sivonen <hsivonen@hsivonen.fi>"]

[features]
simd-accel = ["encoding_rs/simd-accel"]
no-static-ideograph-encoder-tables = ["encoding_rs/no-static-ideograph-encoder-tables"]

[dependencies]
getopts = "0.2.14"
encoding_rs = "0.7.0"
